Import Library

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
import seaborn as sns
from pathlib import Path  

columns settings

In [2]:
pd.options.display.max_columns = None
pd.options.display.max_rows = 200

In [3]:
data = pd.read_csv('dataset/train.csv')
test = pd.read_csv('dataset/test.csv')

Data Preprocessing functions

In [4]:
def remove_NaN_attribute(train_data):
    critical_percentage = 0.25
    # remove Id column first as it is not related to prediction model
    copy_data = train_data.drop('Id', axis=1)
    no_of_data = copy_data.shape[0]
    for attribute in copy_data:
        # count number of NaN item in a attribute
        no_of_NaN_of_attribute_item = copy_data[attribute].isnull().sum()
        if no_of_NaN_of_attribute_item / no_of_data >= critical_percentage:
            print(str(attribute) + ": " + str(no_of_NaN_of_attribute_item / copy_data.shape[0]))
            copy_data = copy_data.drop(attribute, axis=1)
    print(len(copy_data.columns))
    return copy_data

def dropObjectColumns(data):
    object_data = data.select_dtypes(include='object').columns
    dropped_data = data.drop(object_data, axis=1)
    return dropped_data

def sdScaler(data):
    scaler = StandardScaler()
    data_scaled = scaler.fit_transform(data)
    return data_scaled

def makeOneHot(data):
    object_data = data.select_dtypes(include='object').columns
    ohe = OneHotEncoder()
    feature_arr = ohe.fit_transform(data[object_data]).toarray()
    feature_labels = ohe.categories_
    feature_labels = np.hstack(feature_labels)
    features = pd.DataFrame(feature_arr, columns= feature_labels)
    return features

def mode_replace_NaN(data):
    for attribute in data:
        data[attribute] = data[attribute].fillna(data[attribute].mode()[0])
    return data

In [5]:
cleaned_data = remove_NaN_attribute(data)
cleaned_test_data = remove_NaN_attribute(test)

Alley: 0.9376712328767123
FireplaceQu: 0.4726027397260274
PoolQC: 0.9952054794520548
Fence: 0.8075342465753425
MiscFeature: 0.963013698630137
75
Alley: 0.9266620973269363
FireplaceQu: 0.5003427004797807
PoolQC: 0.997943797121316
Fence: 0.8012337217272104
MiscFeature: 0.9650445510623715
74


In [6]:
replaced_data = mode_replace_NaN(cleaned_data)
replaced_test_data = mode_replace_NaN(cleaned_test_data )

filepath = Path('folder/subfolder/out.csv')  
filepath.parent.mkdir(parents=True, exist_ok=True)  
replaced_data.to_csv(filepath)  

In [7]:
dropped_cleaned_scaled_data = dropObjectColumns(replaced_data)
dropped_cleaned_scaled_test_data = dropObjectColumns(replaced_test_data)

In [8]:
X = dropped_cleaned_scaled_data.iloc[:, 0:36]
y = dropped_cleaned_scaled_data.iloc[:, 36]

In [13]:
encoded_columns = makeOneHot(replaced_data)

In [14]:
processed_data = np.concatenate([X, encoded_columns], axis=1)

In [15]:
processed_data

array([[6.000e+01, 6.500e+01, 8.450e+03, ..., 0.000e+00, 1.000e+00,
        0.000e+00],
       [2.000e+01, 8.000e+01, 9.600e+03, ..., 0.000e+00, 1.000e+00,
        0.000e+00],
       [6.000e+01, 6.800e+01, 1.125e+04, ..., 0.000e+00, 1.000e+00,
        0.000e+00],
       ...,
       [7.000e+01, 6.600e+01, 9.042e+03, ..., 0.000e+00, 1.000e+00,
        0.000e+00],
       [2.000e+01, 6.800e+01, 9.717e+03, ..., 0.000e+00, 1.000e+00,
        0.000e+00],
       [2.000e+01, 7.500e+01, 9.937e+03, ..., 0.000e+00, 1.000e+00,
        0.000e+00]])

In [16]:
X_train_scaled = sdScaler(processed_data)
# X_test_scaled = sdScaler(X_test)

In [18]:
pd.DataFrame(X_train_scaled)

0         1         2         3         4         5         6    \
0     0.073375 -0.146189 -0.207142  0.651479 -0.517200  1.050994  0.878668   
1    -0.872563  0.524992 -0.091886 -0.071836  2.179628  0.156734 -0.429577   
2     0.073375 -0.011953  0.073480  0.651479 -0.517200  0.984752  0.830215   
3     0.309859 -0.369915 -0.096897  0.651479 -0.517200 -1.863632 -0.720298   
4     0.073375  0.703973  0.375148  1.374795 -0.517200  0.951632  0.733308   
...        ...       ...       ...       ...       ...       ...       ...   
1455  0.073375 -0.280425 -0.260560 -0.071836 -0.517200  0.918511  0.733308   
1456 -0.872563  0.748718  0.266407 -0.071836  0.381743  0.222975  0.151865   
1457  0.309859 -0.101443 -0.147810  0.651479  3.078570 -1.002492  1.024029   
1458 -0.872563 -0.011953 -0.080160 -0.795151  0.381743 -0.704406  0.539493   
1459 -0.872563  0.301265 -0.058112 -0.795151  0.381743 -0.207594 -0.962566   

           7         8         9         10        11        12        13   \
0     0.514104  0.575425 -0.288653 -0.944591 -0.459303 -0.793434  1.161852   
1    -0.570750  1.171992 -0.288653 -0.641228  0.466465  0.257140 -0.795163   
2     0.325915  0.092907 -0.288653 -0.301643 -0.313369 -0.627826  1.189351   
3    -0.570750 -0.499274 -0.288653 -0.061670 -0.687324 -0.521734  0.937276   
4     1.366489  0.463568 -0.288653 -0.174865  0.199680 -0.045611  1.617877   
...        ...       ...       ...       ...       ...       ...       ...   
1455 -0.570750 -0.973018 -0.288653  0.873321 -0.238122 -0.542435  0.795198   
1456  0.087911  0.759659  0.722112  0.049262  1.104925  2.355701 -0.795163   
1457 -0.570750 -0.369871 -0.288653  0.701265  0.215641  0.065656  1.844744   
1458 -0.570750 -0.865548  6.092188 -1.284176  0.046905 -0.218982 -0.795163   
1459 -0.570750  0.847389  1.509640 -0.976285  0.452784  0.241615 -0.795163   

           14        15        16        17        18        19        20   \
0    -0.120242  0.370333  1.107810 -0.241061  0.789741  1.227585  0.163779   
1    -0.120242 -0.482512 -0.819964  3.948809  0.789741 -0.761621  0.163779   
2    -0.120242  0.515013  1.107810 -0.241061  0.789741  1.227585  0.163779   
3    -0.120242  0.383659  1.107810 -0.241061 -1.026041 -0.761621  0.163779   
4    -0.120242  1.299326  1.107810 -0.241061  0.789741  1.227585  1.390023   
...        ...       ...       ...       ...       ...       ...       ...   
1455 -0.120242  0.250402 -0.819964 -0.241061  0.789741  1.227585  0.163779   
1456 -0.120242  1.061367  1.107810 -0.241061  0.789741 -0.761621  0.163779   
1457 -0.120242  1.569647 -0.819964 -0.241061  0.789741 -0.761621  1.390023   
1458 -0.120242 -0.832788  1.107810 -0.241061 -1.026041 -0.761621 -1.062465   
1459 -0.120242 -0.493934  1.107810 -0.241061 -1.026041  1.227585  0.163779   

           21        22        23        24        25        26        27   \
0    -0.211454  0.912210 -0.951226  0.930592  0.311725  0.351000 -0.752176   
1    -0.211454 -0.318683  0.600495 -0.160705  0.311725 -0.060731  1.626195   
2    -0.211454 -0.318683  0.600495  0.849755  0.311725  0.631726 -0.752176   
3    -0.211454  0.296763  0.600495  0.728500  1.650307  0.790804 -0.752176   
4    -0.211454  1.527656  0.600495  0.809337  1.650307  1.698485  0.780197   
...        ...       ...       ...       ...       ...       ...       ...   
1455 -0.211454  0.296763  0.600495  0.768918  0.311725 -0.060731 -0.752176   
1456 -0.211454  0.296763  2.152216 -0.079868  0.311725  0.126420  2.033231   
1457 -0.211454  1.527656  2.152216 -1.575348 -1.026858 -1.033914 -0.752176   
1458 -0.211454 -0.934130 -0.951226 -1.211583 -1.026858 -1.090059  2.168910   
1459 -0.211454 -0.318683 -0.951226 -0.605307 -1.026858 -0.921624  5.121921   

           28        29        30        31        32        33        34   \
0     0.216503 -0.359325 -0.116339 -0.270208 -0.068692 -0.087688 -1.599111   
1    -0.704483 -0.359325 -0.116339 -0.270208 -0.068692 -0.087688 -0.489110   
2    -0.070361 -0.359325 -0.1

In [20]:
# define the model: Init KNN, n_neighbors is by sqrt(Y_test) = 12, but 12 is even number so - 1 = 11
classifier = KNeighborsClassifier(n_neighbors=17, p=663, metric='euclidean')

# fit model
classifier.fit(X , y)

KNeighborsClassifier(metric='euclidean', n_neighbors=17, p=663)

In [21]:
# Predict the test set result
y_pred = classifier.predict(X_test)
pd.DataFrame(y_pred)

0
0    145000
1    200000
2     67000
3     79000
4    150900
..      ...
287   79900
288  215000
289  118500
290  178000
291   58500

[292 rows x 1 columns]

In [ ]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(f1_score(y_test, y_pred, average='macro'))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
0.0005791505791505791


Machine Learning Models

In [ ]:
models = pd.DataFrame(columns=["Model","MAE","MSE","RMSE","R2 Score","RMSE (Cross-Validation)"])

In [ ]:
lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)
predictions = lin_reg.predict(X_test)

mae, mse, rmse, r_squared = evaluation(y_test, predictions)
print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R2 Score:", r_squared)
print("-"*30)
rmse_cross_val = rmse_cv(lin_reg)
print("RMSE Cross-Validation:", rmse_cross_val)

new_row = {"Model": "LinearRegression","MAE": mae, "MSE": mse, "RMSE": rmse, "R2 Score": r_squared, "RMSE (Cross-Validation)": rmse_cross_val}
models = models.append(new_row, ignore_index=True)